/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.AuxiliarDatos.DatosUsuario;
import controlador.Builder.PedidoB;
import controlador.Builder.PedidoBuilder;
import controlador.Observer.EstadoPedido;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Crud;
import modelo.Pedido;
/**
 *
 * @author LENOVO
 */
public class Pedidos extends javax.swing.JFrame {
private EstadoPedido estadoPedido = new EstadoPedido();

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonPedido = new javax.swing.JButton();
        botonPedido1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(136, 117, 142));
        jTable1.setBackground(new java.awt.Color(153, 0, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Salon", "Fecha", "Hora", "Total "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botonPedido.setBackground(new java.awt.Color(112, 102, 108));
        botonPedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPedido.setText("Realizar el Pedido");
        botonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedidoActionPerformed(evt);
            }
        });

        botonPedido1.setBackground(new java.awt.Color(255, 102, 0));
        botonPedido1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPedido1.setText("Ver Datos");
        botonPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(botonPedido))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(botonPedido1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonPedido1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedido1ActionPerformed
    DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
tableModel.setRowCount(0); 

int idCliente = DatosUsuario.getIdUsuarioSeleccionado();
int idSalon = DatosUsuario.getIdSalonSeleccionado();
double precioConDescuento = DatosUsuario.getPrecioConDescuento(); 

LocalDate fechaActual = LocalDate.now();
LocalTime horaActual = LocalTime.now();

tableModel.addRow(new Object[] { idCliente, idSalon, fechaActual, horaActual, precioConDescuento });

jTable1.setModel(tableModel);
        
    }//GEN-LAST:event_botonPedido1ActionPerformed

    private void botonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedidoActionPerformed
       PedidoBuilder pedidoBuilder = new PedidoBuilder();

    int idCliente = DatosUsuario.getIdUsuarioSeleccionado();
    int idSalon = DatosUsuario.getIdSalonSeleccionado();
    double precioConDescuento = DatosUsuario.getPrecioConDescuento();
    LocalDate fechaActual = LocalDate.now();
    LocalTime horaActual = LocalTime.now();

    PedidoB pedido = pedidoBuilder
        .idCliente(idCliente)
        .idSalon(idSalon)
        .fechaPedido(fechaActual)
        .horaPedido(horaActual)
        .totalPedido(precioConDescuento)
        .estadoPedido("en preparación")
        .build();

    estadoPedido.actualizarEstado("Pedido en preparación");

    Crud listar = new Crud();
    boolean pedidoCreado = false;

    try {
        pedidoCreado = listar.crearPedido(new Pedido(0, pedido.getIdCliente(), pedido.getIdSalon(), pedido.getFechaPedido(), pedido.getHoraPedido(), pedido.getTotalPedido(), pedido.getEstadoPedido()));
    } catch (SQLException ex) {
        Logger.getLogger(Pedidos.class.getName()).log(Level.SEVERE, null, ex);
    }

    if (pedidoCreado) {
        JOptionPane.showMessageDialog(null, "Pedido realizado con éxito. Diríjase al panel de pedidos.");

        estadoPedido.actualizarEstado("Pedido realizado");
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(null, "Error al crear el pedido. Por favor, inténtelo nuevamente.");
    }
        
        
    }//GEN-LAST:event_botonPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPedido;
    private javax.swing.JButton botonPedido1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
